//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIMData
    {
        public string GUID { get; set; }
        public string ElementID { get; set; }
        public string Category { get; set; }
        public string FamilyName { get; set; }
        public string TypeName { get; set; }
        public string Level { get; set; }
        public string BuildingName { get; set; }
        public string ApplianceName { get; set; }
        public string ServiceLife { get; set; }
        public string ProductModel { get; set; }
        public string WarrantyManufacturer { get; set; }
        public string WarrantyDate { get; set; }
        public string WarrantyUnit { get; set; }
        public string CompletionDate { get; set; }
        public string Price { get; set; }
        public string Illustration { get; set; }
        public string Specification { get; set; }
        public string WarrantyPhone { get; set; }
        public string MaintenanceFrequency { get; set; }
        public string Catalog { get; set; }
        public string OMManual { get; set; }
        public string Photo { get; set; }
        public string StandardSize { get; set; }
        public string FireResistance { get; set; }
        public string Source { get; set; }
        public Nullable<int> DBID { get; set; }
        public string MainSystem { get; set; }
        public string SubSystem { get; set; }
        public Nullable<System.DateTime> PWarrantyDate { get; set; }
    }
}
