//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInformation
    {
        public int CI_CSN { get; set; }
        public string CI_RFID { get; set; }
        public string CI_LicensePlateNum { get; set; }
        public string CI_Company { get; set; }
        public string CI_DriverName { get; set; }
        public string CI_CarType { get; set; }
        public string License { get; set; }
        public string ApplyingCheck { get; set; }
        public string Insurance { get; set; }
        public string LaborInsuranceCheck { get; set; }
        public string HazardNotificationCheck { get; set; }
        public string CertificateCheck { get; set; }
        public string CertificateFile { get; set; }
        public string CI_Inspector { get; set; }
        public Nullable<bool> CI_State { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
