//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputationalStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputationalStock()
        {
            this.StockInRecord = new HashSet<StockInRecord>();
            this.StoresRequisitionItem = new HashSet<StoresRequisitionItem>();
        }
    
        public string SISN { get; set; }
        public string StockType { get; set; }
        public string StockName { get; set; }
        public string Unit { get; set; }
        public double StockAmount { get; set; }
        public double MinStockAmount { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInRecord> StockInRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoresRequisitionItem> StoresRequisitionItem { get; set; }
    }
}
