//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_MaintainItemValue
    {
        public string EMIVSN { get; set; }
        public string ESN { get; set; }
        public string MISSN { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> lastMaintainDate { get; set; }
        public Nullable<System.DateTime> NextMaintainDate { get; set; }
        public bool IsCreateForm { get; set; }
    
        public virtual EquipmentInfo EquipmentInfo { get; set; }
        public virtual Template_MaintainItemSetting Template_MaintainItemSetting { get; set; }
    }
}
