//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_MaintenanceForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment_MaintenanceForm()
        {
            this.Equipment_MaintenanceFormMember = new HashSet<Equipment_MaintenanceFormMember>();
        }
    
        public string EMFSN { get; set; }
        public string ESN { get; set; }
        public string MISSN { get; set; }
        public string MaintainName { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> lastMaintainDate { get; set; }
        public System.DateTime NextMaintainDate { get; set; }
        public string Status { get; set; }
        public string Dispatcher { get; set; }
        public Nullable<System.DateTime> DispatcherTime { get; set; }
        public Nullable<System.DateTime> ReportTime { get; set; }
        public string ReportContent { get; set; }
        public string ReportId { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<bool> AuditResult { get; set; }
        public string AuditReason { get; set; }
    
        public virtual EquipmentInfo EquipmentInfo { get; set; }
        public virtual Template_MaintainItemSetting Template_MaintainItemSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_MaintenanceFormMember> Equipment_MaintenanceFormMember { get; set; }
    }
}
