//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentReportForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentReportForm()
        {
            this.InspectionPlanRepair = new HashSet<InspectionPlanRepair>();
            this.ReportImage = new HashSet<ReportImage>();
        }
    
        public string RSN { get; set; }
        public string ESN { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReportLevel { get; set; }
        public string ReportContent { get; set; }
        public string InformatUserID { get; set; }
        public string ReportState { get; set; }
        public Nullable<bool> StockState { get; set; }
        public string ReportSource { get; set; }
    
        public virtual EquipmentInfo EquipmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlanRepair> InspectionPlanRepair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportImage> ReportImage { get; set; }
    }
}
