//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentInfo()
        {
            this.EquipmentReportForm = new HashSet<EquipmentReportForm>();
        }
    
        public string ESN { get; set; }
        public string System { get; set; }
        public string SubSystem { get; set; }
        public string EName { get; set; }
        public string Area { get; set; }
        public string Floor { get; set; }
        public string Room { get; set; }
        public string RoomName { get; set; }
        public string SourceSpace { get; set; }
        public string SourceObject { get; set; }
        public string PropertyCode { get; set; }
        public string Brand { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.DateTime> GuaranteeDeadline { get; set; }
        public string DBID { get; set; }
        public string RFID { get; set; }
        public string EState { get; set; }
        public string FSN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentReportForm> EquipmentReportForm { get; set; }
    }
}
