//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentInfo()
        {
            this.Equipment_AddFieldValue = new HashSet<Equipment_AddFieldValue>();
            this.Equipment_MaintainItemValue = new HashSet<Equipment_MaintainItemValue>();
            this.Equipment_MaintenanceForm = new HashSet<Equipment_MaintenanceForm>();
            this.EquipmentReportForm = new HashSet<EquipmentReportForm>();
            this.InspectionPlan_Equipment = new HashSet<InspectionPlan_Equipment>();
            this.RFID = new HashSet<RFID>();
        }
    
        public string ESN { get; set; }
        public string EName { get; set; }
        public string NO { get; set; }
        public string FSN { get; set; }
        public string Brand { get; set; }
        public string Vendor { get; set; }
        public string Model { get; set; }
        public string ContactPhone { get; set; }
        public string OperatingVoltage { get; set; }
        public string OtherInfo { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string Memo { get; set; }
        public Nullable<int> DBID { get; set; }
        public string GUID { get; set; }
        public string ElementID { get; set; }
        public string EState { get; set; }
        public string TSN { get; set; }
        public bool IsDelete { get; set; }
        public string EPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_AddFieldValue> Equipment_AddFieldValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_MaintainItemValue> Equipment_MaintainItemValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_MaintenanceForm> Equipment_MaintenanceForm { get; set; }
        public virtual Floor_Info Floor_Info { get; set; }
        public virtual Template_OneDeviceOneCard Template_OneDeviceOneCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentReportForm> EquipmentReportForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_Equipment> InspectionPlan_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFID> RFID { get; set; }
    }
}
