//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentalLabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperimentalLabel()
        {
            this.ExperimentalLabel_Item = new HashSet<ExperimentalLabel_Item>();
        }
    
        public string ELSN { get; set; }
        public string TAWSN { get; set; }
        public System.DateTime EDate { get; set; }
        public string UploadUserName { get; set; }
        public System.DateTime UploadDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperimentalLabel_Item> ExperimentalLabel_Item { get; set; }
        public virtual TestingAndAnalysisWorkflow TestingAndAnalysisWorkflow { get; set; }
    }
}
