//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadsetVideo
    {
        public int V_SN { get; set; }
        public string V_Title { get; set; }
        public string V_FileName { get; set; }
        public string V_VideoFile { get; set; }
        public string V_GrapherAccount { get; set; }
        public Nullable<System.DateTime> V_ShootingTime { get; set; }
        public string V_Memo { get; set; }
        public string V_State { get; set; }
        public string Filer { get; set; }
        public Nullable<System.DateTime> FilerTime { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
