//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InquiryOrder()
        {
            this.InquiryOrderItem = new HashSet<InquiryOrderItem>();
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
            this.Quotation1 = new HashSet<Quotation>();
        }
    
        public string IOSN { get; set; }
        public string IOState { get; set; }
        public string QSN { get; set; }
        public string InquiryUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AuditUserID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditContent { get; set; }
        public string AuditResult { get; set; }
        public Nullable<int> QAmount { get; set; }
    
        public virtual Quotation Quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryOrderItem> InquiryOrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotation1 { get; set; }
    }
}
