//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPlanRepair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionPlanRepair()
        {
            this.RepairAuditInfo = new HashSet<RepairAuditInfo>();
            this.RepairCompletionImage = new HashSet<RepairCompletionImage>();
            this.RepairSupplementaryInfo = new HashSet<RepairSupplementaryInfo>();
        }
    
        public string IPRSN { get; set; }
        public string IPSN { get; set; }
        public string RSN { get; set; }
        public string RepairState { get; set; }
        public string RepairUserID { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public string RepairContent { get; set; }
        public string RepairStateOfFilling { get; set; }
    
        public virtual EquipmentReportForm EquipmentReportForm { get; set; }
        public virtual InspectionPlan InspectionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairAuditInfo> RepairAuditInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairCompletionImage> RepairCompletionImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairSupplementaryInfo> RepairSupplementaryInfo { get; set; }
    }
}
