//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPlan_Time
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionPlan_Time()
        {
            this.InspectionPlan_Equipment = new HashSet<InspectionPlan_Equipment>();
            this.InspectionPlan_Member = new HashSet<InspectionPlan_Member>();
            this.InspectionPlan_RFIDOrder = new HashSet<InspectionPlan_RFIDOrder>();
        }
    
        public string IPTSN { get; set; }
        public string IPSN { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string PlanPathSN { get; set; }
        public string PathName { get; set; }
        public int InspectionNum { get; set; }
        public int Frequency { get; set; }
        public string InspectionState { get; set; }
    
        public virtual InspectionPathSample InspectionPathSample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_Equipment> InspectionPlan_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_Member> InspectionPlan_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_RFIDOrder> InspectionPlan_RFIDOrder { get; set; }
    }
}
