//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPlanMaintain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionPlanMaintain()
        {
            this.MaintainAuditInfo = new HashSet<MaintainAuditInfo>();
            this.MaintainCompletionImage = new HashSet<MaintainCompletionImage>();
            this.MaintainSupplementaryInfo = new HashSet<MaintainSupplementaryInfo>();
        }
    
        public string IPMSN { get; set; }
        public string IPSN { get; set; }
        public string EMFISN { get; set; }
        public string MaintainState { get; set; }
        public string MaintainUserID { get; set; }
        public Nullable<System.DateTime> MaintainDate { get; set; }
        public string MaintainContent { get; set; }
        public string MaintainStateOfFilling { get; set; }
    
        public virtual EquipmentMaintainFormItem EquipmentMaintainFormItem { get; set; }
        public virtual InspectionPlan InspectionPlan { get; set; }
        public virtual InspectionPlan InspectionPlan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintainAuditInfo> MaintainAuditInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintainCompletionImage> MaintainCompletionImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintainSupplementaryInfo> MaintainSupplementaryInfo { get; set; }
    }
}
