//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPlan_Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionPlan_Equipment()
        {
            this.InspectionPlan_EquipmentCheckItem = new HashSet<InspectionPlan_EquipmentCheckItem>();
            this.InspectionPlan_EquipmentReportingItem = new HashSet<InspectionPlan_EquipmentReportingItem>();
            this.InspectionPlan_RFIDOrder = new HashSet<InspectionPlan_RFIDOrder>();
        }
    
        public string IPESN { get; set; }
        public string IPTSN { get; set; }
        public string ESN { get; set; }
        public string ReportUserName { get; set; }
        public Nullable<System.DateTime> FillinTime { get; set; }
    
        public virtual EquipmentInfo EquipmentInfo { get; set; }
        public virtual InspectionPlan_Time InspectionPlan_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_EquipmentCheckItem> InspectionPlan_EquipmentCheckItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_EquipmentReportingItem> InspectionPlan_EquipmentReportingItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_RFIDOrder> InspectionPlan_RFIDOrder { get; set; }
    }
}
