//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPlan_RFIDOrder
    {
        public string InspectionOrder { get; set; }
        public string IPTSN { get; set; }
        public string IPESN { get; set; }
        public string RFIDInternalCode { get; set; }
        public string Status { get; set; }
    
        public virtual InspectionPlan_Equipment InspectionPlan_Equipment { get; set; }
        public virtual InspectionPlan_Time InspectionPlan_Time { get; set; }
        public virtual RFID RFID { get; set; }
    }
}
