//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionTrack
    {
        public string ITSN { get; set; }
        public string PMSN { get; set; }
        public string Arae { get; set; }
        public string Floor { get; set; }
        public decimal LocationX { get; set; }
        public decimal LocationY { get; set; }
        public System.DateTime Date { get; set; }
        public int Heartbeat { get; set; }
        public int StepNum { get; set; }
    
        public virtual InspectionPlanMember InspectionPlanMember { get; set; }
    }
}
