//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPlanPath
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionPlanPath()
        {
            this.DrawInspectionPlanPath = new HashSet<DrawInspectionPlanPath>();
            this.InspectionPlanFloorPath = new HashSet<InspectionPlanFloorPath>();
        }
    
        public string PSN { get; set; }
        public string IPSN { get; set; }
        public string PathTitle { get; set; }
        public string FSN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawInspectionPlanPath> DrawInspectionPlanPath { get; set; }
        public virtual InspectionPlan InspectionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlanFloorPath> InspectionPlanFloorPath { get; set; }
    }
}
