//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPathSample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionPathSample()
        {
            this.DailyInspectionSampleContent = new HashSet<DailyInspectionSampleContent>();
            this.InspectionDefaultOrder = new HashSet<InspectionDefaultOrder>();
            this.InspectionPlan_Time = new HashSet<InspectionPlan_Time>();
        }
    
        public string PlanPathSN { get; set; }
        public string PathName { get; set; }
        public int Frequency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyInspectionSampleContent> DailyInspectionSampleContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionDefaultOrder> InspectionDefaultOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlan_Time> InspectionPlan_Time { get; set; }
    }
}
