//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintainAuditInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintainAuditInfo()
        {
            this.MaintainAuditImage = new HashSet<MaintainAuditImage>();
        }
    
        public string PMASN { get; set; }
        public string IPMSN { get; set; }
        public string AuditUserID { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditMemo { get; set; }
        public string AuditResult { get; set; }
        public bool IsBuffer { get; set; }
    
        public virtual InspectionPlanMaintain InspectionPlanMaintain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintainAuditImage> MaintainAuditImage { get; set; }
    }
}
