//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingMinutes
    {
        public string MMSN { get; set; }
        public string MeetingTopic { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public System.DateTime MeetingDateStart { get; set; }
        public System.DateTime MeetingDateEnd { get; set; }
        public string MeetingVenue { get; set; }
        public string Chairperson { get; set; }
        public string Participant { get; set; }
        public int ExpectedAttendence { get; set; }
        public int ActualAttendence { get; set; }
        public int AbsenteeList { get; set; }
        public string TakeTheMinutes { get; set; }
        public string Agenda { get; set; }
        public string MeetingContent { get; set; }
        public string MeetingFiles { get; set; }
        public string UploadUserName { get; set; }
        public System.DateTime UploadDateTime { get; set; }
    }
}
