//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bimfm_MinSheng_MISEntities : DbContext
    {
        public Bimfm_MinSheng_MISEntities()
            : base("name=Bimfm_MinSheng_MISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AreaInfo> AreaInfo { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CompletionReportImage> CompletionReportImage { get; set; }
        public virtual DbSet<ComputationalStock> ComputationalStock { get; set; }
        public virtual DbSet<DeliveryRecord> DeliveryRecord { get; set; }
        public virtual DbSet<DrawInspectionPlanPath> DrawInspectionPlanPath { get; set; }
        public virtual DbSet<DrawPathSample> DrawPathSample { get; set; }
        public virtual DbSet<EquipmentInfo> EquipmentInfo { get; set; }
        public virtual DbSet<EquipmentMaintainFormItem> EquipmentMaintainFormItem { get; set; }
        public virtual DbSet<EquipmentMaintainItem> EquipmentMaintainItem { get; set; }
        public virtual DbSet<EquipmentReportForm> EquipmentReportForm { get; set; }
        public virtual DbSet<Floor_Info> Floor_Info { get; set; }
        public virtual DbSet<InquiryOrder> InquiryOrder { get; set; }
        public virtual DbSet<InquiryOrderItem> InquiryOrderItem { get; set; }
        public virtual DbSet<InquiryOrderSubItem> InquiryOrderSubItem { get; set; }
        public virtual DbSet<InspectionPlan> InspectionPlan { get; set; }
        public virtual DbSet<InspectionPlanFloorPath> InspectionPlanFloorPath { get; set; }
        public virtual DbSet<InspectionPlanMaintain> InspectionPlanMaintain { get; set; }
        public virtual DbSet<InspectionPlanMember> InspectionPlanMember { get; set; }
        public virtual DbSet<InspectionPlanPath> InspectionPlanPath { get; set; }
        public virtual DbSet<InspectionPlanRepair> InspectionPlanRepair { get; set; }
        public virtual DbSet<InspectionTrack> InspectionTrack { get; set; }
        public virtual DbSet<MaintainAuditImage> MaintainAuditImage { get; set; }
        public virtual DbSet<MaintainAuditInfo> MaintainAuditInfo { get; set; }
        public virtual DbSet<MaintainCompletionImage> MaintainCompletionImage { get; set; }
        public virtual DbSet<MaintainItem> MaintainItem { get; set; }
        public virtual DbSet<MaintainSupplementaryFile> MaintainSupplementaryFile { get; set; }
        public virtual DbSet<MaintainSupplementaryInfo> MaintainSupplementaryInfo { get; set; }
        public virtual DbSet<ManufacturerInfo> ManufacturerInfo { get; set; }
        public virtual DbSet<PathSample> PathSample { get; set; }
        public virtual DbSet<PathSampleOrder> PathSampleOrder { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItem { get; set; }
        public virtual DbSet<PurchaseRequisition> PurchaseRequisition { get; set; }
        public virtual DbSet<PurchaseRequisitionItem> PurchaseRequisitionItem { get; set; }
        public virtual DbSet<Quotation> Quotation { get; set; }
        public virtual DbSet<QuotationFiles> QuotationFiles { get; set; }
        public virtual DbSet<QuotationItem> QuotationItem { get; set; }
        public virtual DbSet<RepairAuditImage> RepairAuditImage { get; set; }
        public virtual DbSet<RepairAuditInfo> RepairAuditInfo { get; set; }
        public virtual DbSet<RepairCompletionImage> RepairCompletionImage { get; set; }
        public virtual DbSet<RepairSupplementaryFile> RepairSupplementaryFile { get; set; }
        public virtual DbSet<RepairSupplementaryInfo> RepairSupplementaryInfo { get; set; }
        public virtual DbSet<ReportImage> ReportImage { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockInRecord> StockInRecord { get; set; }
        public virtual DbSet<StockOutItem> StockOutItem { get; set; }
        public virtual DbSet<StockOutRecord> StockOutRecord { get; set; }
        public virtual DbSet<StoresRequisition> StoresRequisition { get; set; }
        public virtual DbSet<StoresRequisitionItem> StoresRequisitionItem { get; set; }
        public virtual DbSet<SubSystemManagement> SubSystemManagement { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemManagement> SystemManagement { get; set; }
    }
}
