//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bimfm_MinSheng_MISEntities : DbContext
    {
        public Bimfm_MinSheng_MISEntities()
            : base("name=Bimfm_MinSheng_MISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeaconData> BeaconData { get; set; }
        public virtual DbSet<BeaconDevice> BeaconDevice { get; set; }
        public virtual DbSet<UserHeartRhythmData> UserHeartRhythmData { get; set; }
        public virtual DbSet<UserPositionData> UserPositionData { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AreaInfo> AreaInfo { get; set; }
        public virtual DbSet<AsBuiltDrawing> AsBuiltDrawing { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BIMData> BIMData { get; set; }
        public virtual DbSet<ComputationalStock> ComputationalStock { get; set; }
        public virtual DbSet<DailyInspectionSample> DailyInspectionSample { get; set; }
        public virtual DbSet<DailyInspectionSampleContent> DailyInspectionSampleContent { get; set; }
        public virtual DbSet<DesignDiagrams> DesignDiagrams { get; set; }
        public virtual DbSet<DrawingSubSystemManagement> DrawingSubSystemManagement { get; set; }
        public virtual DbSet<DrawingSystemManagement> DrawingSystemManagement { get; set; }
        public virtual DbSet<Equipment_AddFieldValue> Equipment_AddFieldValue { get; set; }
        public virtual DbSet<Equipment_MaintainItemValue> Equipment_MaintainItemValue { get; set; }
        public virtual DbSet<Equipment_MaintenanceForm> Equipment_MaintenanceForm { get; set; }
        public virtual DbSet<Equipment_MaintenanceFormMember> Equipment_MaintenanceFormMember { get; set; }
        public virtual DbSet<Equipment_ReportFormMember> Equipment_ReportFormMember { get; set; }
        public virtual DbSet<EquipmentInfo> EquipmentInfo { get; set; }
        public virtual DbSet<EquipmentOperatingManual> EquipmentOperatingManual { get; set; }
        public virtual DbSet<EquipmentReportForm> EquipmentReportForm { get; set; }
        public virtual DbSet<ExperimentalData> ExperimentalData { get; set; }
        public virtual DbSet<ExperimentalDataRecord> ExperimentalDataRecord { get; set; }
        public virtual DbSet<ExperimentalLabel> ExperimentalLabel { get; set; }
        public virtual DbSet<ExperimentalLabel_Item> ExperimentalLabel_Item { get; set; }
        public virtual DbSet<Floor_Info> Floor_Info { get; set; }
        public virtual DbSet<InspectionDefaultOrder> InspectionDefaultOrder { get; set; }
        public virtual DbSet<InspectionPathSample> InspectionPathSample { get; set; }
        public virtual DbSet<InspectionPlan> InspectionPlan { get; set; }
        public virtual DbSet<InspectionPlan_Equipment> InspectionPlan_Equipment { get; set; }
        public virtual DbSet<InspectionPlan_EquipmentCheckItem> InspectionPlan_EquipmentCheckItem { get; set; }
        public virtual DbSet<InspectionPlan_EquipmentReportingItem> InspectionPlan_EquipmentReportingItem { get; set; }
        public virtual DbSet<InspectionPlan_Member> InspectionPlan_Member { get; set; }
        public virtual DbSet<InspectionPlan_RFIDOrder> InspectionPlan_RFIDOrder { get; set; }
        public virtual DbSet<InspectionPlan_Time> InspectionPlan_Time { get; set; }
        public virtual DbSet<InspectionTrack> InspectionTrack { get; set; }
        public virtual DbSet<LaboratoryMaintenance> LaboratoryMaintenance { get; set; }
        public virtual DbSet<ManufacturerInfo> ManufacturerInfo { get; set; }
        public virtual DbSet<MeetingMinutes> MeetingMinutes { get; set; }
        public virtual DbSet<MonthlyReport> MonthlyReport { get; set; }
        public virtual DbSet<RFID> RFID { get; set; }
        public virtual DbSet<StockChangesRecord> StockChangesRecord { get; set; }
        public virtual DbSet<StockType> StockType { get; set; }
        public virtual DbSet<Template_AddField> Template_AddField { get; set; }
        public virtual DbSet<Template_CheckItem> Template_CheckItem { get; set; }
        public virtual DbSet<Template_MaintainItemSetting> Template_MaintainItemSetting { get; set; }
        public virtual DbSet<Template_OneDeviceOneCard> Template_OneDeviceOneCard { get; set; }
        public virtual DbSet<Template_ReportingItem> Template_ReportingItem { get; set; }
        public virtual DbSet<TestingAndAnalysis_DataName> TestingAndAnalysis_DataName { get; set; }
        public virtual DbSet<TestingAndAnalysis_LabelName> TestingAndAnalysis_LabelName { get; set; }
        public virtual DbSet<TestingAndAnalysisWorkflow> TestingAndAnalysisWorkflow { get; set; }
        public virtual DbSet<Tokens> Tokens { get; set; }
        public virtual DbSet<WarningMessage> WarningMessage { get; set; }
        public virtual DbSet<WarningMessageFillinRecord> WarningMessageFillinRecord { get; set; }
        public virtual DbSet<WatchPairing> WatchPairing { get; set; }
    }
}
