//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bimfm_MinSheng_MISEntities : DbContext
    {
        public Bimfm_MinSheng_MISEntities()
            : base("name=Bimfm_MinSheng_MISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AreaInfo> AreaInfo { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CameraData> CameraData { get; set; }
        public virtual DbSet<CarInformation> CarInformation { get; set; }
        public virtual DbSet<CarInOut> CarInOut { get; set; }
        public virtual DbSet<CompletionReportImage> CompletionReportImage { get; set; }
        public virtual DbSet<DrawInspectionPlanPath> DrawInspectionPlanPath { get; set; }
        public virtual DbSet<DrawPathSample> DrawPathSample { get; set; }
        public virtual DbSet<EnviData> EnviData { get; set; }
        public virtual DbSet<EquipmentInfo> EquipmentInfo { get; set; }
        public virtual DbSet<EquipmentMaintainFormItem> EquipmentMaintainFormItem { get; set; }
        public virtual DbSet<EquipmentMaintainItem> EquipmentMaintainItem { get; set; }
        public virtual DbSet<EquipmentReportForm> EquipmentReportForm { get; set; }
        public virtual DbSet<Floor_Info> Floor_Info { get; set; }
        public virtual DbSet<HeadsetVideo> HeadsetVideo { get; set; }
        public virtual DbSet<ImspectionPlanFloorPath> ImspectionPlanFloorPath { get; set; }
        public virtual DbSet<InspectionPlan> InspectionPlan { get; set; }
        public virtual DbSet<InspectionPlanMaintain> InspectionPlanMaintain { get; set; }
        public virtual DbSet<InspectionPlanMember> InspectionPlanMember { get; set; }
        public virtual DbSet<InspectionPlanPath> InspectionPlanPath { get; set; }
        public virtual DbSet<InspectionPlanRepair> InspectionPlanRepair { get; set; }
        public virtual DbSet<InspectionTrack> InspectionTrack { get; set; }
        public virtual DbSet<MaintainAuditImage> MaintainAuditImage { get; set; }
        public virtual DbSet<MaintainAuditInfo> MaintainAuditInfo { get; set; }
        public virtual DbSet<MaintainCompletionImage> MaintainCompletionImage { get; set; }
        public virtual DbSet<MaintainItem> MaintainItem { get; set; }
        public virtual DbSet<MaintainSupplementaryFile> MaintainSupplementaryFile { get; set; }
        public virtual DbSet<MaintainSupplementaryInfo> MaintainSupplementaryInfo { get; set; }
        public virtual DbSet<PathSample> PathSample { get; set; }
        public virtual DbSet<PathSampleOrder> PathSampleOrder { get; set; }
        public virtual DbSet<PersonInfomaton> PersonInfomaton { get; set; }
        public virtual DbSet<PersonInOut> PersonInOut { get; set; }
        public virtual DbSet<RepairAuditImage> RepairAuditImage { get; set; }
        public virtual DbSet<RepairAuditInfo> RepairAuditInfo { get; set; }
        public virtual DbSet<RepairCompletionImage> RepairCompletionImage { get; set; }
        public virtual DbSet<RepairSupplementaryFile> RepairSupplementaryFile { get; set; }
        public virtual DbSet<RepairSupplementaryInfo> RepairSupplementaryInfo { get; set; }
        public virtual DbSet<ReportImage> ReportImage { get; set; }
        public virtual DbSet<SubSystemManagement> SubSystemManagement { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemManagement> SystemManagement { get; set; }
        public virtual DbSet<TemporaryCarApply> TemporaryCarApply { get; set; }
        public virtual DbSet<TemporaryCarRFID> TemporaryCarRFID { get; set; }
        public virtual DbSet<TemporaryPersonApply> TemporaryPersonApply { get; set; }
        public virtual DbSet<TemporaryPersonRFID> TemporaryPersonRFID { get; set; }
        public virtual DbSet<UserInformation> UserInformation { get; set; }
    }
}
