//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyReport
    {
        public string MRSN { get; set; }
        public string ReportTitle { get; set; }
        public string ReportContent { get; set; }
        public string UploadUserName { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public string ReportFile { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
    }
}
