//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInOut
    {
        public int PIO_SN { get; set; }
        public string PIO_RFID { get; set; }
        public string PIO_Company { get; set; }
        public string PIO_Name { get; set; }
        public string PIO_Title { get; set; }
        public string PI_MSN { get; set; }
        public string TPA_SN { get; set; }
        public string EntrySite { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public string LeaveSite { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
    }
}
