//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfomaton
    {
        public int PI_MSN { get; set; }
        public string PI_RFID { get; set; }
        public string PI_Company { get; set; }
        public string PI_Name { get; set; }
        public string PI_Phone { get; set; }
        public string PI_Case { get; set; }
        public string PI_ID { get; set; }
        public string PI_Title { get; set; }
        public string PI_BloodType { get; set; }
        public string PI_Contact { get; set; }
        public string PI_EmergentPhone { get; set; }
        public string PI_Photo { get; set; }
        public Nullable<bool> PI_ApplyingCheck { get; set; }
        public string PI_ApplyingFile { get; set; }
        public Nullable<bool> PI_PhysicalCheck { get; set; }
        public string PI_PhysicalFile { get; set; }
        public Nullable<bool> PI_TrainingCheck { get; set; }
        public string PI_TrainingFile { get; set; }
        public Nullable<bool> PI_InsuranceCheck { get; set; }
        public string PI_InsuranceFile { get; set; }
        public string PI_Memo { get; set; }
        public Nullable<System.DateTime> PI_Status { get; set; }
        public Nullable<bool> PI_State { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
