//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequisition()
        {
            this.PurchaseRequisitionItem = new HashSet<PurchaseRequisitionItem>();
        }
    
        public string PRN { get; set; }
        public string PRUserName { get; set; }
        public string PRState { get; set; }
        public string PRDept { get; set; }
        public System.DateTime PRDate { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public string AuditUserID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequisitionItem> PurchaseRequisitionItem { get; set; }
    }
}
