//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderItem()
        {
            this.StockInRecord = new HashSet<StockInRecord>();
        }
    
        public string POISN { get; set; }
        public string POSN { get; set; }
        public string Kind { get; set; }
        public string ItemName { get; set; }
        public string Size { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public double Amount { get; set; }
        public string Packaging { get; set; }
        public string State { get; set; }
        public string AcceptResult { get; set; }
        public string AcceptRecord { get; set; }
        public string Memo { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInRecord> StockInRecord { get; set; }
    }
}
