//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisitionItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequisitionItem()
        {
            this.InquiryOrderSubItem = new HashSet<InquiryOrderSubItem>();
        }
    
        public string PRIN { get; set; }
        public string PRN { get; set; }
        public string PRIState { get; set; }
        public string Kind { get; set; }
        public string ItemName { get; set; }
        public string Size { get; set; }
        public double PRAmount { get; set; }
        public string Unit { get; set; }
        public string ApplicationPurpose { get; set; }
        public string AuditResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryOrderSubItem> InquiryOrderSubItem { get; set; }
        public virtual PurchaseRequisition PurchaseRequisition { get; set; }
    }
}
