//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationItem
    {
        public string QISN { get; set; }
        public string QSN { get; set; }
        public string IOISN { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Packaging { get; set; }
        public Nullable<int> SubTotal { get; set; }
    
        public virtual InquiryOrderItem InquiryOrderItem { get; set; }
        public virtual Quotation Quotation { get; set; }
    }
}
