//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quotation()
        {
            this.InquiryOrder = new HashSet<InquiryOrder>();
            this.QuotationFiles = new HashSet<QuotationFiles>();
            this.QuotationItem = new HashSet<QuotationItem>();
        }
    
        public string QSN { get; set; }
        public string IOSN { get; set; }
        public int ExcludeTaxTotal { get; set; }
        public Nullable<int> IncludeTaxTotal { get; set; }
        public string MFRName { get; set; }
        public string ContactPerson { get; set; }
        public string MFRTelNO { get; set; }
        public string MFRMBPhone { get; set; }
        public string MFRMainProduct { get; set; }
        public string MFRAddress { get; set; }
        public string MFREmail { get; set; }
        public string MFRWeb { get; set; }
        public string PaymentMethod { get; set; }
        public string DeliveryMethod { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryOrder> InquiryOrder { get; set; }
        public virtual InquiryOrder InquiryOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationFiles> QuotationFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationItem> QuotationItem { get; set; }
    }
}
