//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFID
    {
        public string RFIDInternalCode { get; set; }
        public string SARSN { get; set; }
        public string ESN { get; set; }
        public string RFIDExternalCode { get; set; }
        public string FSN { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Location_X { get; set; }
        public Nullable<decimal> Location_Y { get; set; }
        public string Memo { get; set; }
    
        public virtual EquipmentInfo EquipmentInfo { get; set; }
        public virtual Floor_Info Floor_Info { get; set; }
        public virtual StockChangesRecord StockChangesRecord { get; set; }
    }
}
