//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.StockOutItem = new HashSet<StockOutItem>();
        }
    
        public string SSN { get; set; }
        public string SIRSN { get; set; }
        public string SISN { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public double Amount { get; set; }
        public double RemainingAmount { get; set; }
        public string RFIDInternalCode { get; set; }
    
        public virtual ComputationalStock ComputationalStock { get; set; }
        public virtual StockInRecord StockInRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutItem> StockOutItem { get; set; }
    }
}
