//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockOutRecord()
        {
            this.StockOutItem = new HashSet<StockOutItem>();
        }
    
        public string SORSN { get; set; }
        public string SRSN { get; set; }
        public string StockOutUserName { get; set; }
        public string ReceiverUserName { get; set; }
        public string StockOutContent { get; set; }
        public Nullable<System.DateTime> StockOutDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutItem> StockOutItem { get; set; }
        public virtual StoresRequisition StoresRequisition { get; set; }
    }
}
