//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoresRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoresRequisition()
        {
            this.StockOutRecord = new HashSet<StockOutRecord>();
            this.StoresRequisitionItem = new HashSet<StoresRequisitionItem>();
        }
    
        public string SRSN { get; set; }
        public string SRState { get; set; }
        public string SRUserName { get; set; }
        public string SRDept { get; set; }
        public System.DateTime SRDateTime { get; set; }
        public string SRContent { get; set; }
        public string AuditUserID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutRecord> StockOutRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoresRequisitionItem> StoresRequisitionItem { get; set; }
    }
}
