//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLogs
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string UserId { get; set; }
        public byte[] Client_IP { get; set; }
        public string Request { get; set; }
        public string HttpMethod { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Result { get; set; }
        public string Data { get; set; }
    }
}
