//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemporaryPersonApply
    {
        public string TPA_SN { get; set; }
        public string TPR_RFID { get; set; }
        public string TPA_Company { get; set; }
        public string TPA_Name { get; set; }
        public string TPA_Phone { get; set; }
        public string TPA_Title { get; set; }
        public string TPA_BloodType { get; set; }
        public string TPA_Contact { get; set; }
        public string TPA_EmergentPhone { get; set; }
        public string TPA_Photo { get; set; }
        public string TPA_Inspector { get; set; }
        public Nullable<System.DateTime> TPA_InspectorDate { get; set; }
        public Nullable<System.DateTime> TPA_StartDate { get; set; }
        public Nullable<System.DateTime> TPA_EndDate { get; set; }
        public string TPA_Memo { get; set; }
        public string TPA_State { get; set; }
        public string Filer { get; set; }
        public Nullable<System.DateTime> FilerTime { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    }
}
