//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_MaintainItemSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template_MaintainItemSetting()
        {
            this.Equipment_MaintainItemValue = new HashSet<Equipment_MaintainItemValue>();
            this.Equipment_MaintenanceForm = new HashSet<Equipment_MaintenanceForm>();
        }
    
        public string MISSN { get; set; }
        public string TSN { get; set; }
        public string MaintainName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_MaintainItemValue> Equipment_MaintainItemValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_MaintenanceForm> Equipment_MaintenanceForm { get; set; }
        public virtual Template_OneDeviceOneCard Template_OneDeviceOneCard { get; set; }
    }
}
