//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_ReportingItem
    {
        public string RISN { get; set; }
        public string TSN { get; set; }
        public string ReportingItemName { get; set; }
        public string Unit { get; set; }
    
        public virtual Template_OneDeviceOneCard Template_OneDeviceOneCard { get; set; }
    }
}
