//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingAndAnalysisWorkflow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestingAndAnalysisWorkflow()
        {
            this.ExperimentalDataRecord = new HashSet<ExperimentalDataRecord>();
            this.ExperimentalLabel = new HashSet<ExperimentalLabel>();
            this.TestingAndAnalysis_DataName = new HashSet<TestingAndAnalysis_DataName>();
            this.TestingAndAnalysis_LabelName = new HashSet<TestingAndAnalysis_LabelName>();
        }
    
        public string TAWSN { get; set; }
        public string ExperimentType { get; set; }
        public string ExperimentName { get; set; }
        public string WorkflowFile { get; set; }
        public string UploadUserName { get; set; }
        public System.DateTime UploadDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperimentalDataRecord> ExperimentalDataRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperimentalLabel> ExperimentalLabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestingAndAnalysis_DataName> TestingAndAnalysis_DataName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestingAndAnalysis_LabelName> TestingAndAnalysis_LabelName { get; set; }
    }
}
