//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_EquipmentInfo
    {
        public string ESN { get; set; }
        public string Ename { get; set; }
        public string NO { get; set; }
        public string FSN { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string WarrantyManufacturer { get; set; }
        public string ServiceLife { get; set; }
        public string WarrantyPhone { get; set; }
        public string Vendor { get; set; }
        public string ContactPhone { get; set; }
        public string OperatingVoltage { get; set; }
        public string OtherInfo { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public string AssetNumber { get; set; }
        public string Memo { get; set; }
        public Nullable<int> DBID { get; set; }
        public string GUID { get; set; }
        public string ElementID { get; set; }
        public string Estate { get; set; }
        public string TSN { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Ephoto { get; set; }
    }
}
