//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int U_SN { get; set; }
        public string U_Name { get; set; }
        public string U_Email { get; set; }
        public string U_Phone { get; set; }
        public string U_Account { get; set; }
        public string U_PassWord { get; set; }
        public string U_Company { get; set; }
        public string PI_MSN { get; set; }
        public string U_Permission { get; set; }
        public Nullable<bool> U_PswState { get; set; }
        public Nullable<bool> U_State { get; set; }
        public string Filer { get; set; }
        public Nullable<System.DateTime> FilerTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Updater { get; set; }
    }
}
