//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarningMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarningMessage()
        {
            this.WarningMessageFillinRecord = new HashSet<WarningMessageFillinRecord>();
        }
    
        public string WMSN { get; set; }
        public string WMType { get; set; }
        public string WMState { get; set; }
        public System.DateTime TimeOfOccurrence { get; set; }
        public string FSN { get; set; }
        public string Message { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarningMessageFillinRecord> WarningMessageFillinRecord { get; set; }
    }
}
